version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ashish
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: ashish
